sonar.projectKey=TaskManagementAPI
sonar.working.directory=D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\TaskManagementSystem\\TaskManagementAPI
sonar.pullrequest.cache.basepath=D:\\TaskManagementSystem\\TaskManagementAPI
sonar.sources=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.vs\\TaskManagementAPI.slnx\\config\\applicationhost.config",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.vs\\TaskManagementAPI.slnx\\v18\\DocumentLayout.backup.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.vs\\TaskManagementAPI.slnx\\v18\\DocumentLayout.json"

8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.projectKey=TaskManagementAPI:8AFDF02E-CF18-4459-D717-8AF5E39FEEB0
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.projectName=TaskManagementAPI
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.projectBaseDir=D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.sourceEncoding=utf-8
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.tests=
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.sources=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Controllers\\AuthController.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Controllers\\TaskController.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Controllers\\UserController.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Data\\AppDbContext.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\DTOS\\CreateTaskDto.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\DTOS\\loginDto.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\DTOS\\RegisterDto.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\DTOS\\UpdateProfileDto.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\DTOS\\UpdateTaskDto.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\TaskItem.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Models\\Users.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Program.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Services\\jwtservice.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Swagger\\ExampleOperationFilter.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\TaskManagementAPI.GlobalUsings.g.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\TaskManagementAPI.AssemblyInfo.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\TaskManagementAPI.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\appsettings.Development.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\appsettings.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Logs\\log-20260416.txt",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\TaskManagementAPI.http",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\Properties\\launchSettings.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\project.assets.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\TaskManagementAPI.csproj.nuget.dgspec.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\bin\\Debug\\net10.0\\appsettings.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\bin\\Debug\\net10.0\\TaskManagementAPI.deps.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\bin\\Debug\\net10.0\\TaskManagementAPI.runtimeconfig.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\bin\\Debug\\net10.0\\TaskManagementAPI.staticwebassets.endpoints.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\ApiEndpoints.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\TaskManagementAPI.sourcelink.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI\\obj\\Debug\\net10.0\\EndpointInfo\\TaskManagementAPI.json"

8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.cs.analyzer.projectOutPaths=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\0",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\2"
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.cs.roslyn.reportFilePaths=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\0\\Issues.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\2\\Issues.json"
8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.cs.scanner.telemetry=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\0\\Telemetry.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\2\\Telemetry.json"

8AFDF02E-CF18-4459-D717-8AF5E39FEEB0.sonar.working.directory=D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\.sonar\\mod0
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.projectKey=TaskManagementAPI:788B3E8D-C33D-466D-934D-0EC1449CCB36
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.projectName=TaskManagementAPI.tests
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.projectBaseDir=D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.sourceEncoding=utf-8
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.sources=
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.tests=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\obj\\project.assets.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\obj\\TaskManagementAPI.tests.csproj.nuget.dgspec.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\appsettings.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\TaskManagementAPI.deps.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\TaskManagementAPI.runtimeconfig.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\TaskManagementAPI.staticwebassets.endpoints.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\TaskManagementAPI.tests.deps.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\bin\\Debug\\net10.0\\TaskManagementAPI.tests.runtimeconfig.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\obj\\Debug\\net10.0\\TaskManagementAPI.tests.sourcelink.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\Controllers\\AuthControllerTest.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\Controllers\\TaskControllerTest.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\Controllers\\UserControllerTest.cs",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\TaskManagementAPI.tests\\Services\\jwtservicetests.cs"

788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.cs.analyzer.projectOutPaths=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\1",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\3"
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.cs.roslyn.reportFilePaths=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\1\\Issues.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\3\\Issues.json"
788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.cs.scanner.telemetry=\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\1\\Telemetry.json",\
"D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\3\\Telemetry.json"

788B3E8D-C33D-466D-934D-0EC1449CCB36.sonar.working.directory=D:\\TaskManagementSystem\\TaskManagementAPI\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/obj/**,**/bin/**,**/.vs/**,**/Migrations/**,**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=8AFDF02E-CF18-4459-D717-8AF5E39FEEB0,788B3E8D-C33D-466D-934D-0EC1449CCB36

